### ISSUE TITLE
Stylus version? Mirrors?

### ISSUE THREAD

**Issue by afonsopacifer** [milligram/milligram-stylus#1]
Essa versão será um tipo de mirror da versão original, utilizando stylus > sass?
Se for o caso eu posso ajudar :)

Mas se for isso mesmo, você não acha que vai ficar um pouco dificil de manter, tipo vários mirros em várias "linguagens"?

Enfim, 
parabêns pelo projeto :)

**Comment by cjpatoilo** [comment]
Hello @afonsopacifer 

Exactly! The support will be the same as the main repository. At first it was difficult to structure everything, but now is well organized. Your help is very welcome, already thank you for your power.

==============

Olá @afonsopacifer 

Exatamente! O suporte será o mesmo do repositório principal. No início foi difícil estrutura tudo, mas agora já está bem organizado. Sua ajuda é muito bem-vinda, desde já obrigado pela sua força.
